Ask to run dbrestore immediately after dbdump

diff --git a/bin/dbdump b/bin/dbdump
--- a/bin/dbdump
+++ b/bin/dbdump
@@ -18,3 +18,18 @@ source <(echo "$ENV")
 ssh $1 "mysqldump -h $DB_HOST -u $DB_USERNAME -p$DB_PASSWORD $DB_DATABASE | gzip -9" > $1.sql.gz
 gunzip $1.sql.gz
 echo "$1.sql"
+
+read -r -p "Run 'dbrestore $1.sql'? [y/N] " input
+
+case $input in
+    [yY][eE][sS]|[yY])
+ dbrestore $1.sql
+ ;;
+    [nN][oO]|[nN]|"")
+ exit 1
+ ;;
+    *)
+ echo "Invalid input..."
+ exit 1
+ ;;
+esac
